# Configuração do Tema
theme: jekyll-theme-cayman

# Metadados da Página (Opcional, mas recomendado)
title: 5 Lições de Liderança do USS Benfold
description: "Lições de um comandante da Marinha que vão transformar sua equipe."
